name: BuyBox
main: com.noheroes.buybox.BuyBox
version: 0.2
author: cjwazzy
depend: [Vault]
commands:
  buybox:
    description: BuyBox setup commands
    aliases: [bbox, bbx]
    usage: Type /buybox help for more information. Aliases include /bbox and /bbx
    