name: BuyBox
main: com.noheroes.buybox.BuyBox
version: 0.8
author: cjwazzy
depend: [Vault]
commands:
  buybox:
    description: BuyBox setup commands for admins.  Use /buybox help for more
    aliases: [bbox, bbx]
    usage: Type /buybox help for more information. Aliases include /bbox and /bbx
permissions:
  buybox.admin:
    description: Allows admin to set purchase orders
    default: op
    